<?php
// +-------------------------------------------------+
// © 2011-2012 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
// +-------------------------------------------------+
// $Id: pmb_reader.module,v 1.9 2011-10-21 20:32:23 gueluneau Exp $

include drupal_get_path('module', 'pmb_reader').'/pmb_reader_forms.inc';
require drupal_get_path('module', 'pmb_reader').'/pmb_reader_templates.tpl.php';

function pmb_reader_help($path, $arg) {
  $output = '';  //declare your output variable
  switch ($path) {
    case "admin/help#pmb_reader":
      $output = '<p>'.  t("Ce module n'inclut pas d'aide") .'</p>';
      break;
  }
  return $output;
} 

//function pmb_reader_perm() {
//  return array(
//  	'pmb search catalog',
//  );
//} 

function pmb_reader_form_user_login_alter( &$form, $form_state ){
    unset($form['links']);
    $form['#validate'] = array(  'user_login_name_validate', 'pmb_reader_auth_login_validate', 'user_login_final_validate' );
}

//function pmb_reader_form_user_pass_alter( &$form, $form_state ){
//    unset($form['links']);
//    //$form['#validate'] = array('pmb_reader_pass_validate', 'user_pass_validate' );
//    $form['#submit'] = array('pmb_reader_pass_submit');
//}
//
//function pmb_reader_pass_validate(&$form, $form_state){
//
//	$name = trim($form_state['values']['name']);
//	// Try to load by email.
//	$account = user_load(array('mail' => $name, 'status' => 1));
//	if (!$account) {
//		// No success, try to load by name.
//		$account = user_load(array('name' => $name, 'status' => 1));
//	}
//	// si c'est un compte PMB
//	if(!isset($account->pmb_credentials)){
//		array_shift($form['#submit']);
//	}else{
//		array_pop($form['#submit']);
//	}
//	//highlight_string(print_r($form,true));
//	//highlight_string(print_r($form_state,true));
//}
//
//
//function pmb_reader_pass_submit($form, &$form_state){
//	$name = trim($form_state['values']['name']);
//
//	// Try to load by email.
//	$account = user_load(array('mail' => $name, 'status' => 1));
//	if (!$account) {
//		// No success, try to load by name.
//		$account = user_load(array('name' => $name, 'status' => 1));
//	}
//	// si c'est un compte PMB
//	if(isset($account->pmb_credentials)){
//		//TODO pmb mail mot de passe oublié
//	}else{
//		user_pass_submit($form, &$form_state);
//	} 
//	return;
//}


function pmb_reader_form_user_login_block_alter( &$form, $form_state ){
	return pmb_reader_form_user_login_alter( $form, $form_state );
}

function pmb_reader_auth_login_validate( $form, &$form_state ){
    $username = $form_state['values']['name'];
    $password = $form_state['values']['pass'];

    require_once(drupal_get_path('module', 'pmb').'/classes/pmb_data.inc');
    $pmb_data = new pmb_data();

    $pmb_sess_id = $pmb_data->reader_sessid($username, $password);

    if ($pmb_sess_id) {
		user_external_login_register($username, 'pmb_reader');
    	$user = user_load(array('name' => $username));
		$reader_info = $pmb_data->reader_get_account_info($pmb_sess_id);
		$to_save = array(
			'pmb_session' => array('sessid' => $pmb_sess_id, 'sessid_date' => time()),
			'pmb_credentials' => array('login' => $username, 'password' => $password),
		);
		if ($reader_info) {
			if (isset($reader_info->personal_information->email) && $reader_info->personal_information->email)
				$to_save['mail'] = $reader_info->personal_information->email;
			$to_save['pmb_reader_info'] = $reader_info;
		}
		user_save($user, $to_save);
		user_authenticate_finalize($form_state['values']);
    }
    else {
        user_login_authenticate_validate( $form, $form_state );
    }
}



function pmb_reader_user_is_reader($user) {
	return isset($user->pmb_reader_info);
}

function pmb_reader_menu() {
  $items = array();

  // definition for main page
  $items['pmb_reader/%user_uid_optional'] =
    array(
      'title' => t('My Reader Account'),
      'description' => t('View and interract with your reader account'),
      'page callback' => 'pmb_reader_reader_information',
      'page arguments' => array(1),
      'access callback' => 'pmb_reader_user_is_reader',
      'access arguments' => array(1),
  	  'file' => 'pmb_reader_account.inc',      
    );
  $items['pmb_reader/%user/summary'] =
    array(
      'title' => t('Summary'),
      'description' => t('Summary of your reader account'),
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'weight' => 0,
    );
  $items['pmb_reader/%user/loans'] =
    array(
      'title' => t('Loans'),
      'description' => t('Your loans'),
      'access callback' => 'pmb_reader_user_is_reader',
      'access arguments' => array(1),
      'page callback' => 'pmb_reader_loans',
      'page arguments' => array(1),
      'type' => MENU_LOCAL_TASK,
      'weight' => 2,
      'file' => 'pmb_reader_account.inc',
    );
  $items['pmb_reader/%user/reservations'] =
    array(
      'title' => t('Reservations'),
      'description' => t('Your reservations'),
      'access callback' => 'pmb_reader_user_is_reader',
      'access arguments' => array(1),
      'page callback' => 'pmb_reader_reservations',
      'page arguments' => array(1),
      'type' => MENU_LOCAL_TASK,
      'weight' => 2,
      'file' => 'pmb_reader_reservations.inc',
    );
  $items['pmb_reader/%user/suggestions'] =
    array(
      'title' => t('Suggestions'),
      'description' => t('Your suggestions'),
      'access callback' => 'pmb_reader_user_is_reader',
      'access arguments' => array(1),
      'page callback' => 'pmb_reader_suggestions',
      'page arguments' => array(1),
      'type' => MENU_LOCAL_TASK,
      'weight' => 2,
      'file' => 'pmb_reader_suggestions.inc',
    );
    
  $items['pmb_reader/%user/delete_reservation/%'] =
    array(
      'access callback' => 'pmb_reader_user_is_reader',
      'access arguments' => array(1),
      'page callback' => 'pmb_reader_delete_reservation',
      'page arguments' => array(1,3),
      'type' => MENU_CALLBACK,
      'weight' => 2,
      'file' => 'pmb_reader_reservations.inc',
    );
    
  $items['pmb_reader/%user/add_reservation/%'] =
    array(
      'access callback' => 'pmb_reader_user_is_reader',
      'access arguments' => array(1),
      'page callback' => 'pmb_reader_add_reservation',
      'page arguments' => array(1,3),
      'type' => MENU_CALLBACK,
      'weight' => 2,
      'file' => 'pmb_reader_reservations.inc',
    );

  $items['pmb_reader/%user/suggestions/%'] =
    array(
      'title' => t('Suggestion'),
      'description' => t('View a suggestions'),
      'access callback' => 'pmb_reader_user_is_reader',
      'access arguments' => array(1),
      'page callback' => 'pmb_reader_suggestion_edit',
      'page arguments' => array(1,3),
      'type' => MENU_CALLBACK,
      'weight' => 2,
      'file' => 'pmb_reader_suggestions.inc',
    );    

    $items['pmb_reader/%user/reading_lists'] =
    array(
      'title' => t('Reading Lists'),
      'description' => t('View your reading lists'),
      'access callback' => 'pmb_reader_user_is_reader',
      'access arguments' => array(1),
      'page callback' => 'pmb_reader_view_reading_lists',
      'page arguments' => array(1),
      'type' => MENU_LOCAL_TASK,
      'weight' => 2,
      'file' => 'pmb_reader_reading_lists.inc',
    );
    
    $items['pmb_reader/%user/reading_lists/%'] =
    array(
      'title' => t('Reading List'),
      'description' => t('View your reading list'),
      'access callback' => 'pmb_reader_user_is_reader',
      'access arguments' => array(1),
      'page callback' => 'pmb_reader_view_reading_list',
      'page arguments' => array(1,3),
      'type' => MENU_CALLBACK,
      'weight' => 2,
      'file' => 'pmb_reader_reading_lists.inc',
    );
    
    $items['pmb_reader/%user/public_reading_lists'] =
    array(
      'title' => t('Public Reading Lists'),
      'description' => t('View public reading lists'),
      'access callback' => 'pmb_reader_user_is_reader',
      'access arguments' => array(1),
      'page callback' => 'pmb_reader_view_public_reading_lists',
      'page arguments' => array(1),
      'type' => MENU_CALLBACK,
      'weight' => 2,
      'file' => 'pmb_reader_reading_lists.inc',
    );
    
    $items['pmb_reader/%user/public_reading_lists/%'] =
    array(
      'title' => t('Public Reading List'),
      'description' => t('View a public reading list'),
      'access callback' => 'pmb_reader_user_is_reader',
      'access arguments' => array(1),
      'page callback' => 'pmb_reader_view_public_reading_list',
      'page arguments' => array(1,3),
      'type' => MENU_CALLBACK,
      'weight' => 2,
      'file' => 'pmb_reader_reading_lists.inc',
    );
    
  $items['pmb_reader/%user/cart'] =
    array(
      'title' => t('Cart'),
      'description' => t('View the content of your cart'),
      'access callback' => 'pmb_reader_user_is_reader',
      'access arguments' => array(1),
      'page callback' => 'pmb_reader_view_cart',
      'page arguments' => array(1),
      'type' => MENU_LOCAL_TASK,
      'weight' => 2,
      'file' => 'pmb_reader_cart.inc',
    );
    
    
  return $items;
}

/*function pmb_reader_profile_alter(&$account) {
	//highlight_string(print_r($account, true));
	//$account->content['summary2'] = $account->content['summary'];
}*/

/**
 * Implementation of hook_user().
 */
/*function pmb_reader_user($type, &$edit, &$user) {
  if ($type == 'view' && isset($user->pmb_reader_info)) {
    $user->content['summary']['pmb_reader_info'] =  array(
      '#type' => 'user_profile_item',
      '#title' => 'PMB reader profile',
      '#value' => 'lapin',
    );
  }
}*/


function pmb_reader_theme() {
  return array(
    'pmb_reader_reader_account_summary' => array(
      'arguments' => array(
  		'reader' => null,
  		'parameters' => null,
      )
    ),
    'pmb_reader_reader_account_loans' => array(
      'arguments' => array(
  		'reader' => null,
    	'loans' => null,
  		'parameters' => null,
      )
    ),
    'pmb_reader_reader_account_reservations' => array(
       'arguments' => array(
  		'reader' => null,
    	'reservations' => null,
  		'parameters' => null,
      )
    ),
    'pmb_reader_reader_account_suggestions' => array(
      'arguments' => array(
  		'reader' => null,
    	'suggestions' => null,
  		'parameters' => null,
      )
    ),
    'pmb_reader_reader_reading_lists' => array(
      'arguments' => array(
  		'reader' => null,
    	'reading_lists' => null,
  		'parameters' => null,
      )
    ),
    'pmb_reader_reader_reading_list' => array(
      'arguments' => array(
  		'reader' => null,
    	'reading_list' => null,
    	'notices' => null,
  		'parameters' => null,
      )
    ),
    'pmb_reader_reader_public_reading_lists' => array(
      'arguments' => array(
  		'reader' => null,
    	'reading_lists' => null,
  		'parameters' => null,
      )
    ),
    'pmb_reader_reader_public_reading_list' => array(
      'arguments' => array(
  		'reader' => null,
    	'reading_list' => null,
    	'notices' => null,
  		'parameters' => null,
      ),
    ),
    'pmb_reader_cart_form' => array(
      'arguments' => array(
    	'form' => null,
      ),
    ),
    'pmb_reader_reading_list_form' => array(
      'arguments' => array(
    	'form' => null,
      ),
    ),
  );
}
